# TODO: Remove when Railway uses PNPM v11.
packages:
  - .

registries:
  '@maiertech': https://npm.pkg.github.com/

minimumReleaseAgeExclude:
  - '@maiertech/sveltekit-helpers'

allowBuilds:
  esbuild: true
  sharp: true
